### ISSUE TITLE
USR2 starts new healthcheck process but doesn't terminate the current one

### ISSUE THREAD

**Issue by mzealey** [Exa-Networks/exabgp#1006]
**Describe the bug**

When I `kill -USR2` exabgp the config reloads and a new healthcheck process is started, but the old ones stick around.

**To Reproduce**

I have a process set up like:

```
process healthcheck {
        run python3 -m exabgp healthcheck --no-syslog --ip xxx --next-hop xxx --cmd "true" --no-ip-setup --community "xxx" --up-metric 400 --withdraw-on-down;
        encoder text;
}
```

I see the following debug output when sending reload signal to exabgp:

```
18:17:39 | 1      | reactor       | SIGUSR2 received
18:17:39 | 1      | reactor       | scheduling reload of configuration and processes
18:17:39 | 1      | configuration | performing reload of exabgp 4.2.11
18:17:39 | 1      | configuration | > process          | 'healthcheck'
18:17:39 | 1      | configuration | . run              | 'python3' '-m' 'exabgp' 'healthcheck' '--no-syslog' ...
18:17:39 | 1      | configuration | . encoder          | 'text'
18:17:39 | 1      | configuration | < process          | 
18:17:39 | 1      | configuration | > template         | 
...
18:17:39 | 1      | reactor       | peer definition identical, updating peer routes if required for neighbor xxx ... family-allowed in-open
18:17:39 | 1      | reactor       | loaded new configuration successfully
18:17:39 | 1      | process       | terminating process healthcheck
INFO[healthcheck] send announces for EXIT state to ExaBGP
18:17:39 | 1      | process       | forked process healthcheck
INFO[healthcheck] send announces for UP state to ExaBGP
18:17:41 | 1      | process       | command from process healthcheck : announce route xxx 
```

A ps then shows:

```
nobody    741593  0.0  0.0  12128 11200 pts/0    S    14:24   0:00 /usr/local/bin/python3 -m exabgp healthcheck ...
nobody    741647  0.0  0.0  12128 11268 pts/0    S    14:24   0:00 /usr/local/bin/python3 -m exabgp healthcheck...
nobody    741872  0.0  0.0  12128 11284 pts/0    S    14:25   0:00 /usr/local/bin/python3 -m exabgp healthcheck ...
nobody    741915  0.0  0.0  12488 11568 pts/0    S    14:25   0:00 /usr/local/bin/python3 -m exabgp healthcheck ...
... many more
```

**Expected behavior**

It should be terminating the process once the new healthcheck has taken over

**Environment (please complete the following information):**

 - OS: Linux, container based off python:3.9-alpine
 - Version 4.2.11

**Comment by thomas-mangin** [comment]
Thank you for this bug report.

**Comment by thomas-mangin** [comment]
@vincentbernat I am sure you know about this trick (and must have a blog entry about init collecting zombie processes but it was to make sure you noticed the patch and are happy with it) :-)

**Comment by mzealey** [comment]
Thanks I only recently learnt this in a different context so forgot to update the ticket but yeah makes sense we probably should have fixed by starting container with `--init` or something

**Comment by thomas-mangin** [comment]
@mzealey .. ah, the container case, if you run in a container that does not have an init to perform this collection I am not sure what we can do to detect the issue and stop it. I would assume that micro-containers these days do provide a simple init which does that ... otherwise bad bad container 😜

**Comment by vincentbernat** [comment]
I am unsure if this is the right fix. I think we should investigate why the process is being reparented to init. Is ExaBGP killing itself during reload? I'll try to investigate a bit, but this may hide either a bug in healthcheck process or in ExaBGP. In the later case, it would be better to fix it inside ExaBGP.

**Comment by mzealey** [comment]
I'll have a check what happens when we run with --initOn 14 Mar 2021 21:29, Vincent Bernat ***@***.***> wrote:
I am unsure if this is the right fix. I think we should investigate why the process is being reparented to init. Is ExaBGP killing itself during reload? I'll try to investigate a bit, but this may hide either a bug in healthcheck process or in ExaBGP. In the later case, it would be better to fix it inside ExaBGP.

**Comment by thomas-mangin** [comment]
@vincentbernat

**Comment by thomas-mangin** [comment]
@vincentbernat good point. I just have limited time atm, it is indeed more a band-aid than a real investigation in the root-cause, so re-opened for further investigation.

**Comment by vincentbernat** [comment]
So, I had a look and for me, the process is not reparented:

```
 19:47 ❱ ps auxf
USER         PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
bernat       805  0.2  0.0  12320  6200 ?        S    19:40   0:01 /usr/bin/zsh-static -i -l
bernat      1134  0.0  0.0   9396  3148 ?        R+   19:47   0:00  \_ ps auxf
bernat         1  0.1  0.0   9092  5032 pts/0    Ss   19:37   0:00 /bin/zsh-static
bernat      1005  1.2  0.0 103068 21704 pts/0    Sl+  19:44   0:02 python3 -m exabgp server --verbose /tmp/api-announce.co
bernat      1008  0.0  0.0  29068 21384 pts/0    S    19:44   0:00  \_ python3 -m exabgp healthcheck --no-syslog --ip 1.1.
bernat      1025  0.1  0.0  29324 21628 pts/0    S    19:44   0:00  \_ python3 -m exabgp healthcheck --no-syslog --ip 1.1.
```

The old process lingers around because it tries to gracefully shutdown:

```
19:44:45 1005   process         terminating process add-remove
INFO[healthcheck] send announces for EXIT state to ExaBGP
DEBUG[healthcheck] exabgp: withdraw route 1.1.1.1/32 next-hop self
```

However, I suppose ExaBGP stops listening to the pipe, even if it's still open:

```
 19:47 ❱ lsof -n | grep 2969467
python3   1005              bernat    5r  FIFO   0,12      0t0 2969467 pipe
python3   1005 1024 python3 bernat    5r  FIFO   0,12      0t0 2969467 pipe
python3   1008              bernat    1w  FIFO   0,12      0t0 2969467 pipe
```

And therefore, it does not send back the awaited ack before exit. And the old process waits forever. I think the clean solution would be for ExaBGP to wait a bit before finishing the reload phase. It would be easy to wait for the `_terminate` thread with a short timeout to let the process acknowledge and even forcibly kill it if it doesn't. However, I am unsure if at this stage, ExaBGP would still be listening to the pipe. Also, when several processes are present, this may take some time to shutdown properly all processes. Thomas, what do you think?

An alternative, would be to just force kill the old process. I'll do a patch for that since it's easy, but it would be nice to let ExaBGP gracefully shutdowns the process. Notably, it would be able to withdraw routes that are not valid anymore instead of leaving them as is.
