### ISSUE TITLE
Healthcheck fails if ExaBGP PID is 1

### ISSUE THREAD

**Issue by jethrogb** [Exa-Networks/exabgp#1062]
In ExaBGP 4.2.13 a regression was introduced where the healthcheck process fails if the ExaBGP PID is 1 (like it would be if you're running ExaBGP in a container).

https://github.com/Exa-Networks/exabgp/blob/4.2/lib/exabgp/application/healthcheck.py#L617

Introduced in 700f06b14e2daa07148a39877f38bae630d2754b and 314b788f569a1761f5f1db98e6640eb028b11dee. Related: #1006. Reverted in master in b810e489ed4edff90c37156899113d0f74aa2b26 but not in 4.2.

**Comment by thomas-mangin** [comment]
ExaBGP should never be run as PID 1. 

Googling "pid 1 in containers zombie reaping problem" gave me this as first hit:
https://blog.phusion.nl/2015/01/20/docker-and-the-pid-1-zombie-reaping-problem/

**Comment by jethrogb** [comment]
This is not a problem, subprocesses are reaped correctly on GC (in Processes._terminate)

**Comment by jethrogb** [comment]
And even if it didn't, not running as PID 1 wouldn't help with that. If ExaBGP didn't reap its child processes correctly, they would remain until ExaBGP itself exited.

**Comment by statik** [comment]
@jethrogb I have found using https://github.com/krallin/tini as pid 1 helpful in similar situations, just mentioning it in case that's useful for you.

**Comment by thomas-mangin** [comment]
The fact that something is possible does not mean it should be done. The debate about running programs as PID 1 in containers is not going to go away anytime soon.

I had not reviewed the Dockerfile for ExaBGP and I will fix it to not run the way it does right now.

**Comment by thomas-mangin** [comment]
> This is not a problem, Python subprocesses are reaped correctly on GC (in Processes._terminate)

The process(es) ran by ExaBGP could have spawned some other processes themselves.

**Comment by thomas-mangin** [comment]
> And even if it didn't, not running as PID 1 wouldn't help with that. If ExaBGP didn't reap its child processes correctly, they would remain until ExaBGP itself exited.

Yes, and it would take quite some time for a few thousand of them to cause issues, that's why some people do not care and this is why the debate will never end, both positions have valid arguments.

I take the position that under all Unix systems PID 1 is `init` and IMHO containers are not special enough to require application writers to deal with PID 1 not being `init`, mostly when there is no issue having an init in containers.

I appreciate that not everyone will agree with this position but I have to take one and this is the one I am taking.

**Comment by jethrogb** [comment]
Why do you even need to take a position as an application developer? Just don't assign special significance to PID 1 and everyone is happy.

**Comment by thomas-mangin** [comment]
Not everyone would be happy, healthcheck does what it should in a correct unix environments it terminates if it detect that exabgp died (for example as it was killed by the kernel due to an out of memory issue) and its processes were then connected to init. PID 1 has significance. You are free to run an os without it but please do not ask me to support systems where PID 1 is not init as otherwise we can not detect the case described above which is also a real world scenario.

**Comment by jethrogb** [comment]
If you want to check this by PID checking, you just need to check if the PPID has changed since start. But an even better way would be to rely on a closed pipe/connection to detect the parent going away.

**Comment by thomas-mangin** [comment]
Let's agree to disagree.
