### ISSUE TITLE
I have a use case to build RPM for RHEL9, First I have downloaded the source.tar.gz and used the redhat spec file.

### ISSUE THREAD

**Issue by raonelakurti** [Exa-Networks/exabgp#1166]
I have a use case to build RPM for RHEL9, First I have downloaded the source.tar.gz and used the redhat spec file.

**To Reproduce**

I have used following spec.file, 
`https://raw.githubusercontent.com/Exa-Networks/exabgp/main/redhat/python-exabgp.spec`

**Expected behavior**

Expectation is build and rpm in the RPM folder.

**Environment (please complete the following information):**

 - OS: [RHEL9]

```
Error:

+ DOCDIR=/Users/rnelakurti/rpmbuild/BUILDROOT/exabgp-4.2.16-1.el9.x86_64/usr/share/doc/exabgp-exabgp
+ export LC_ALL=C
+ LC_ALL=C
+ export DOCDIR
+ /usr/bin/mkdir -p /Users/rnelakurti/rpmbuild/BUILDROOT/exabgp-4.2.16-1.el9.x86_64/usr/share/doc/exabgp-exabgp
+ cp -pr README.md /Users/rnelakurti/rpmbuild/BUILDROOT/exabgp-4.2.16-1.el9.x86_64/usr/share/doc/exabgp-exabgp
+ RPM_EC=0
++ jobs -p
+ exit 0


RPM build errors:
    File not found: /Users/rnelakurti/rpmbuild/BUILDROOT/exabgp-4.2.16-1.el9.x86_64/usr/share/exabgp*
```

When I have checked the path under  /Users/rnelakurti/rpmbuild/BUILDROOT/exabgp-4.2.16-1.el9.x86_64/usr/share/ I didn't see exabgp  binaries didn't exist. And also checked /Users/rnelakurti/rpmbuild/BUILDROOT/exabgp-4.2.16-1.el9.x86_64/usr/sbin/ exabgp binaries exist. I have tried multiple combinations to over the issue, I am out of options. 

@thomas-mangin

**Comment by garybuhrmaster** [comment]
While not directly responsive to your issue, a recent version of the 4.2 branch (4.2.21) is available in EPEL9 (currently only in updates-testing as it has not yet received sufficient karma to be pushed to stable).  If you want to try to use the EPEL9 version of exabgp, you can issue a command of the form:

```
dnf --refresh --enablerepo=epel-testing install exabgp
```

The packaging has been modified from the generic spec file on this site to use (what the RH python packagers call) "modern" python build macros available in Fedora and EL9, along with various other RH distro specific adjustments (all distros have slight differences in packaging preferences).

Since it uses the modern python build macros which are only available in recent releases (and some people may still be using older exabgp releases in older OS releases) it is not clear if a PR to update to the modern build macros is appropriate for this repo (although opinions are welcome), but you can, of course, look at the spec file in the package to see how it is working.

It is the intention of the Fedora exabgp packager (that would be me) to keep the EPEL9 version in sync with the latest exabgp version(s) until/unless some dependencies cannot be met.

**Comment by bmanikantareddy** [comment]
@garybuhrmaster is it possible to get a spec file that have required changes to support epel9
