### ISSUE TITLE
New configuration parser

### ISSUE THREAD

**Issue by thomas-mangin** [Exa-Networks/exabgp#139]
Have a better, more deterministic configuration parser opening the way for other improvements.

**Comment by thomas-mangin** [comment]
Code has started on this. The whole parser is being rewritten. It still creates a dictionary tree which is then used to generate the Python Object. The objectives / steps to completion are:
- finish this parser to get feature parity with the current one
- remove the intermediary dictionary creation ( it will improve performance )
- then possible change the core to use ijson to have a JSON configuration format and not a hand made one ( this should also improve performance)

**Comment by icb-** [comment]
If it's not too late, I would like to vote for the config language **not** being JSON. JSON is great  between a webserver and client-side Javascript, but its lack of comments makes it unsuitable for a config file. There are a couple "workarounds" for this, namely duplicating keys (which don't survive a deserialize/serialize operation) and naming conventions (prefixing comments with `_`, which can get out of order and detached from the statement they describe). Neither of these workarounds helps in an array.

My personal choice would be [YAML](http://yaml.org/), but even XML is a step up from JSON, strictly because of comments.

**Comment by thomas-mangin** [comment]
I need to look at how the code works but I would expect to be able to 'pre-process' the file to allo the current use of # comments. I will update this thread before making any irreversible changes.

**Comment by pyke369** [comment]
Here is a short excerpt of a code that would just allow JSON with comments (in different forms like leading #, leading //, C-like /* */) and fix trailing , before block closing. Easy-peasy enough.

```
conf = {}
try:
    handle  = open(conf_path, 'r')
    content = handle.read(65536)
    handle.close()
    content = re.sub(r'^\s*(#|//).+?$', '', content, flags = re.M)
    content = re.sub(r'/\*[^\*]*\*/', '', content)
    content = re.sub(r',(\s*[\}\]])', r'\1', content)
    conf    = json.loads(content)
except:
    pass

**Comment by thomas-mangin** [comment]
Thank you, and indeed, this would work. It would require the whole JSON file to be loaded fully in memory I would rather have a progressive parser. I will comment more when I have investigated more.

**Comment by clickfreak** [comment]
How about YAML for config file? It's easy to read (for humans and machines), and has some useful internal features (anchors, etc) for large configurations. JSON <-> YAML is very easy.

**Comment by thomas-mangin** [comment]
The text processor should ideally be interchangeable ( JSON and YAML are two ways to present the same underlying HashTable, List, etc ).

**Comment by thomas-mangin** [comment]
Code has started and is very much under-way so closing the isue.
