### ISSUE TITLE
logging customization

### ISSUE THREAD

**Issue by jtkdpu** [Exa-Networks/exabgp#234]
A few requests related to ExaBGP logging.

 * It should be possible to set the facility for syslog output.
 * The log level is generally best determined by the application itself and not set as  global value for all log messages by the user.
 * The format of messages sent to syslog is seemingly incorrect or suboptimal.

This last point needs some clarification.  For instance, when an update arrives, my syslog gets something like this:

  Fri, 27 Feb 2015 16:25:58 | INFO     | 18299  | routes        | peer 192.0.2.1 ASN 64496   << UPDATE (2)

Note, this time stamp and the remainder of the message is after the syslog prepends a time stamp and system name.  It is as if the message to the logger device isn't be properly presented.  It would also be best to present a single program name (e.g. exabgp) and then simply have a standard format so that "routes", "reactor" or whatever can be easily identified as part of that well formed message.  In this specific example, it might also be helpful to identify the local peering information, in case there is more than one local listener or distinct local peering information of a set so you know what session this is associated.with.

The only place I see an openlog() method is in etc/exabgp/processes/syslog-1.py with the ExaBGP ident, but I don't see that ident in any logs.

Is the idea that those helper scripts should be used to handle proper syslog messaging?  That seems a little hacky if so.  :-)

It might be worth noting that dev/configuration/first.exa and dev/configuration/first.exa both refer to a a syslog-2.py helper script, but that script doesn't exist.

John

**Comment by thomas-mangin** [comment]
Hi John, Thank you for taking some time and making suggestions to improve ExaBGP. I will try to address your requests with some code at some point.

I have no machine which is sending output to syslog so I have never had a look at what it looks like since the initial implementation, it may indeed be sub-optimal.

The log information was primarily designed for STDOUT/STDERR logging with something like daemontools or supervisord handling the outpout of the logs.

It is very common for my own installations to run more than one ExaBGP instance on a same machine. Therefore the output does include the process PID. I was expecting the output on syslog to include the application name .. I will have to check this.

The subsystem information is very useful when debugging to filter lines with grep and filter what is not required.

The logging code is in https://github.com/Exa-Networks/exabgp/blob/master/lib/exabgp/logger.py and any other logger are for the backend process which can be written in any language. The syslog example is to log received routes to syslog.

The dev folder does not contain production code ( it is for in development features and or things I want to keep in the repository but is not required by ExaBGP ) hence why the referenced scripts do not exist anymore. first.exa was an idea for the new format but it will not be that way finally.

**Comment by thomas-mangin** [comment]
was it what you wanted ?
https://github.com/thomas-mangin/exabgp/commit/c0327fa91ad1014f3f330f00985f6b7bcbca13f8
