### ISSUE TITLE
Match Multiple TCP-Flags with Hex value in Flowspec Rules

### ISSUE THREAD

**Issue by jpan613** [Exa-Networks/exabgp#248]
Since the flowspec support in Exabgp is mostly used for DDoS mitigation, it'd be nice to have the ability to match multiple tcp-flags in hex value like on the JunOS platform. For example, a tcp christmas tree packet will have the hex value of 0x29.

**Comment by thomas-mangin** [comment]
Hello,

I have never used tcp-flags but as far as I can see 0x29 is 0x20 + 0x08 + 0x1 which would be setup as [ urgent | push | fin ]. The code must then use the three value in a flow spec rules where they are AND'ed.

Due to the way the code is designed using a single value would require to decompose it in its valid sub-component and this would be a large change in the code.

However using integer instead of the name should be possible such as writing [ 32 8 1 ] I noticed that the code would not accept hex values, but this would be easy to change.

Would allowing [ 0x20 0x8 0x1 ] be acceptable as a solution ? As I am not sure about the use case which lead you to ask for this feature.

**Comment by jpan613** [comment]
Thanks for replying. Allowing [ 0x20 0x8 0x1 ] would be a good solution.
As for use case, attackers use malformed tcp packets for DDoS attack:
https://blogs.akamai.com/2015/01/tcp-flag-ddos-attack-by-lizard-squad-indicates-ddos-tool-development.html
So it's important to have the ability to match and drop them on the edge of the network using flowspec.

**Comment by thomas-mangin** [comment]
Done some refactoring to add the feature, so 1/2 way there ( as I need to be able to know what are valid values for each rule )

**Comment by thomas-mangin** [comment]
The implementation nearly done yesterday and was completed https://github.com/Exa-Networks/exabgp/commit/7c7820cb528b4b09020dbbb0b291491ec5a404c8

I will not backport this change back to 3.4 as it may cause name changes change for flow part (it should not but I prefer to be sure and not break 3.4 installation).

**Comment by jpan613** [comment]
Just got a chance to test this. It looks like when you use tcp-flags [ 0x20 0x8 0x1 ], exabgp OR these flags instead of AND them.
See this output from "show firewall filter __flowspec_default_inet__" on the receiving end of the flowspec rule:
10.0.9.1,10.0.2.102,proto=6,tcp-flag=20,=08,=01,len=24  

Ideally we should see:
10.0.9.1,10.0.2.102,proto=6,tcp-flag=29,len=24

Let me know if that makes sense.
Many thanks!

**Comment by thomas-mangin** [comment]
Ok understood: what I implemented is not what you asked ! I have allowed to use numeric instead of name with the current syntax but not a way to add the number ...

**Comment by thomas-mangin** [comment]
I will allow a new syntax : tcp-flags [ 0x20+0x8+0x1 ]

**Comment by thomas-mangin** [comment]
But you can also use the symbolic names
