### ISSUE TITLE
Feature request: configuring max-prefix limit

### ISSUE THREAD

**Issue by dfox-spb** [Exa-Networks/exabgp#323]
It would be very helpful to have a configuration of max-prefix limit. Per neighbor/per AF.

**Comment by thomas-mangin** [comment]
Currently (and only with a recent master) we only count the number of updates received per peer not routes. 

I think that while it make sense for other BGP implementation - which are used to program a FIB, I am not sure for ExaBGP - your feedback is welcomed.

I will close the issue but if you still care (as it is nearly two years since the request) please feel free to re-open and explain the use case you had in mind.
