### ISSUE TITLE
installation IOError: [Errno 2] No such file or directory: 'PYPI.rst'

### ISSUE THREAD

**Issue by gr0mit1** [Exa-Networks/exabgp#384]
Hi
Am I being dumb?

I do pip install exabgp and it falls over on me:

```
root@librenms:/etc# pip install exabgp
Downloading/unpacking exabgp
  Downloading exabgp-3.4.13.tar.gz (240Kb): 240Kb downloaded
  Running setup.py egg_info for package exabgp
    removing left-over egg
    Traceback (most recent call last):
      File "<string>", line 14, in <module>
      File "/etc/build/exabgp/setup.py", line 287, in <module>
        description_rst = open('PYPI.rst').read() % {'version': version}
    IOError: [Errno 2] No such file or directory: 'PYPI.rst'
    Complete output from command python setup.py egg_info:
    removing left-over egg

Traceback (most recent call last):

  File "<string>", line 14, in <module>

  File "/etc/build/exabgp/setup.py", line 287, in <module>

    description_rst = open('PYPI.rst').read() % {'version': version}

IOError: [Errno 2] No such file or directory: 'PYPI.rst'

----------------------------------------
Command python setup.py egg_info failed with error code 1 in /etc/build/exabgp
Storing complete log in /root/.pip/pip.log
root@librenms:/etc#
```

Any hints please, or is this a bug?

I'm on Debian Wheezy.
root@librenms:/etc# python --version
Python 2.7.3

**Comment by thomas-mangin** [comment]
```
pip install exabgp
Collecting exabgp
  Cache entry deserialization failed, entry ignored
  Downloading exabgp-3.4.13-py2-none-any.whl (336kB)
    100% |████████████████████████████████| 339kB 1.1MB/s
Requirement already satisfied (use --upgrade to upgrade): setuptools in /usr/local/lib/python2.7/site-packages (from exabgp)
Installing collected packages: exabgp
Successfully installed exabgp-3.4.13
You are using pip version 8.0.2, however version 8.1.0 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

**Comment by thomas-mangin** [comment]
@vincentbernat the file on pypi does not contain the PYPI.rst file when the tarball on github does. I fixed this on master (AFAICS - as I never done a release). Can you help ?

**Comment by vincentbernat** [comment]
If you want to reproduce, I think you need to use `--no-use-wheel`.

I am unsure to understand what you are asking but I would be happy to help. :) Since you fixed the problem on master, why not cherry-pick for the 3.4 branch? I would have said that this is something to be added in `MANIFEST.in`, but maybe not.

**Comment by thomas-mangin** [comment]
@vincentbernat Thank you for the prompt answer !

I just had come to the opposite conclusion that he should use pip wheel. As the wheel worked on my mac and the egg failed on debian.

I am due to release a new version of 3.4 as I fixed quite a few bugs (once I understand why travisCI is always failing the test suite when it works with the others CI services I use too)

The issue is that the file in not included in the tarball created by setup.py (and setup.py is not exactly something nice to work on :p)

**Comment by vincentbernat** [comment]
You can create a `MANIFEST.in` files with just `PYPI.rst` in it. Dunno if there is a better way to do that.

**Comment by thomas-mangin** [comment]
It would work but define the included files in two places which is perhaps confusing. I will have a look and think about it. Thanks for the tip !

**Comment by vincentbernat** [comment]
Maybe if it's `MANIFEST.in`, it doesn't need to be in `setup.py`. I agree this is suboptimal, but I am quite rusty on those aspects.

**Comment by thomas-mangin** [comment]
It has already been fixed (following a similar bug report) and I had forgotten.

```
unzip -l exabgp-3.4.15.zip | grep PYPI
     2522  03-08-16 10:36   exabgp-3.4.15/PYPI.rst
```
