### ISSUE TITLE
about advertise vpn routing(with rd) to another vpn

### ISSUE THREAD

**Issue by liuheyang** [Exa-Networks/exabgp#398]
hi,
in our application, exabgp acts as bgp controller, and establish ibgp connection with a router, and with no vpn. in the router, we configure anothter vpn network 
and we want to advertise route into this vpn network. 
   Is It impossible? And how can we implement it?

**Comment by thomas-mangin** [comment]
You are asking BGP questions and not ExaBGP questions. I do support ExaBGP but I am not a BGP consultant. If you find a BUG with ExaBGP, I am happy to fix it otherwise please do not use ExaBGP's issue tracker to get generic BGP support.

From what you wrote, I am not sure I understand your question !  If you are asking if you can send VPN routes to a router on a BGP connection which has not negotiated a AFI/SAFI for VPN routes, the answer is no. if this is not the question, please experiment and find out.

Good luck with your project.
