### ISSUE TITLE
Routes withdrawn when BGP state is down are not removed from the adj-rib-out

### ISSUE THREAD

**Issue by bryanschwerer** [Exa-Networks/exabgp#407]
I've duplicated this with a back-to-back exabgp 3.4.16 setup.  In my case, I'm using vpnv4 routes.  

1)  Annouce route
`announce route 10.0.158.0/24 rd 200:1 next-hop self extended-community 111111111:1 extended-community 4294967295:1 label 26`
2) Kill exabgp on far side
3) Withdraw route on near side
`withdraw route 10.0.158.0/24 rd 200:1 next-hop self  label 26`
4) Using CLI on near side (still there)

> show routes
> 
> routes requested
> 
> neighbor 10.11.13.124 10.0.158.0/24 next-hop 10.64.156.70 label [ 26 ] route-distinguisher 200:1

5) Restart exabgp on far side
6) Withdrawn route is sent to peer
7) Withdraw route again on near side (gone)

> show routes
> routes requested
> 
>  (my addition){empty}

Could this be related to https://github.com/Exa-Networks/exabgp/issues/370 ?

**Comment by thomas-mangin** [comment]
Yes, both are likely related. I will use some "free time" I have this week to investigate.

**Comment by thomas-mangin** [comment]
show routes does show the ADJ-RIB-OUT. the reason is that until the route is sent to the neighbor (ie: until we can write it on the wire), our ADJ-RIB-OUT still has the route as the change received from the process as pending but not done yet.

The withdraw message should not be sent on reconnection and therefore I have a patch for this pending. I will find the tree I put it in and commit it (as I forgot to do).

**Comment by thomas-mangin** [comment]
by the way - sorry - it took me exactly a month to look and fix this issue. This was a long time.

**Comment by MadDog2K** [comment]
@thomas-mangin 

Seems to be not fixed

show routes : 

Mon, 04 Jul 2016 17:23:41 7378   processes     Command from process jafar-exabgp-tcpserver : show routes
Mon, 04 Jul 2016 17:23:41 7378   reactor       callback | handling 'show routes' with show_routes
Mon, 04 Jul 2016 17:23:41 7378   reactor       callback | installing show_routes
Mon, 04 Jul 2016 17:23:41 7378   reactor       callback | running
Mon, 04 Jul 2016 17:23:41 7378   reactor       responding to jafar-exabgp-tcpserver : neighbor 10.86.2.218 10.55.131.0/24 next-hop 100::1
Mon, 04 Jul 2016 17:23:41 7378   reactor       responding to jafar-exabgp-tcpserver : neighbor 10.86.2.218 10.55.131.99/32 next-hop 10.86.2.221
Mon, 04 Jul 2016 17:23:41 7378   reactor       callback | running
Mon, 04 Jul 2016 17:23:41 7378   reactor       responding to jafar-exabgp-tcpserver : neighbor 10.86.2.218 fd00:89f:9999::9999/128 next-hop ::ffff:10.86.2.221
Mon, 04 Jul 2016 17:23:41 7378   reactor       responding to jafar-exabgp-tcpserver : neighbor 10.86.2.218 fd00:89f:9999::/48 next-hop ::ffff:10.86.2.221
Mon, 04 Jul 2016 17:23:41 7378   reactor       callback | running
Mon, 04 Jul 2016 17:23:41 7378   reactor       responding to jafar-exabgp-tcpserver : done
Mon, 04 Jul 2016 17:23:41 7378   reactor       callback | removing

withdraw route 10.55.131.99/32 : 

Mon, 04 Jul 2016 17:23:47 7378   processes     Command from process jafar-exabgp-tcpserver : neighbor 10.86.2.218 withdraw route 10.55.131.99/32
Mon, 04 Jul 2016 17:23:47 7378   reactor       callback | handling 'neighbor 10.86.2.218 withdraw route 10.55.131.99/32' with withdraw_route
Mon, 04 Jul 2016 17:23:47 7378   reactor       callback | installing withdraw_route
Mon, 04 Jul 2016 17:23:47 7378   reactor       callback | running
Mon, 04 Jul 2016 17:23:47 7378   configuration . route            | '10.55.131.99/32'
Mon, 04 Jul 2016 17:23:47 7378   reactor       route removed from neighbor 10.86.2.218 local-ip 10.86.2.221 local-as 65099 peer-as 15879 router-id 10.86.2.221 family-allowed in-open : 10.55.131.99/32 next-hop 0.0.0.0
Mon, 04 Jul 2016 17:23:47 7378   reactor       responding to jafar-exabgp-tcpserver : done
Mon, 04 Jul 2016 17:23:47 7378   reactor       callback | removing
Mon, 04 Jul 2016 17:23:47 7378   reactor       performing dynamic route update
Mon, 04 Jul 2016 17:23:47 7378   reactor       updated peers dynamic routes successfully

Do another 'show routes' : 

Mon, 04 Jul 2016 17:23:49 7378   processes     Command from process jafar-exabgp-tcpserver : show routes
Mon, 04 Jul 2016 17:23:49 7378   reactor       callback | handling 'show routes' with show_routes
Mon, 04 Jul 2016 17:23:49 7378   reactor       callback | installing show_routes
Mon, 04 Jul 2016 17:23:49 7378   reactor       callback | running
Mon, 04 Jul 2016 17:23:49 7378   reactor       responding to jafar-exabgp-tcpserver : neighbor 10.86.2.218 10.55.131.0/24 next-hop 100::1
Mon, 04 Jul 2016 17:23:49 7378   reactor       responding to jafar-exabgp-tcpserver : neighbor 10.86.2.218 10.55.131.99/32 next-hop 10.86.2.221
Mon, 04 Jul 2016 17:23:49 7378   reactor       callback | running
Mon, 04 Jul 2016 17:23:49 7378   reactor       responding to jafar-exabgp-tcpserver : neighbor 10.86.2.218 fd00:89f:9999::9999/128 next-hop ::ffff:10.86.2.221
Mon, 04 Jul 2016 17:23:49 7378   reactor       responding to jafar-exabgp-tcpserver : neighbor 10.86.2.218 fd00:89f:9999::/48 next-hop ::ffff:10.86.2.221
Mon, 04 Jul 2016 17:23:49 7378   reactor       callback | running
Mon, 04 Jul 2016 17:23:49 7378   reactor       responding to jafar-exabgp-tcpserver : done
Mon, 04 Jul 2016 17:23:49 7378   reactor       callback | removing


Route 10.55.131.99/32 is still there

This happens when session with neighbor 10.86.2.218 is flapping (eg. down)

**Comment by thomas-mangin** [comment]
Could you please open another issue to have error 3,3 to cause the route to be removed from the ADJ-RIB-OUT. I am not sure this behaviour is correct and really nowdays the peer should treat-as-withdraw in most case for update correctly formated (which ExaBGP should always do).

**Comment by thomas-mangin** [comment]
This bug should have been fixed a the rib is reset performed during the reset.
