### ISSUE TITLE
Help needed to get started with exabgp

### ISSUE THREAD

**Issue by hieberm** [Exa-Networks/exabgp#580]
I started working with exabgp. My requirements are very simple. I have a Linux VM and I would like to setup a BGP session between the host and the VM. This is the path where I have exabgp

[root@localhost ~]# whereis exabgp
exabgp: /usr/sbin/exabgp /etc/exabgp /usr/share/man/man1/exabgp.1.gz

I wrote a .conf file in /etc/exabgp/exabgp.conf

[root@localhost ~]# cat /etc/exabgp/exabgp.conf 
```
group VM {                         
    router-id 1.2.3.4;              
    
    neighbor 5.6.7.8 {               
        local-address 1.2.3.4;       
        local-as 65000;             
        peer-as 65000;             
    }
    process add-routes {
        run /root/example.py;

    } 
}
```

My script to announce the routes are in /root/example.py and I chmod it to 755

```
#!/usr/bin/env python
 
from sys import stdout
from time import sleep
 
messages = [
'announce route A.A.A.A next-hop self',
'announce route B.B.B.B next-hop self',
]
 
sleep(5)
 
#Iterate through messages
for message in messages:
    stdout.write( message + '\n')
    stdout.flush()
    sleep(1)
 
#Loop endlessly to allow ExaBGP to continue running
while True:
    sleep(1)
```

I am currently running this manually as /usr/sbin/exabgp /etc/exabgp/exabgp.conf

1. Does my conf look correct? I saw it needs to be a conf.ini in some examples. Where should the conf file be?
2. Does my example script look correct? Again where should I put the script, any suggested path.
3. I did not have  a exabgp.env, so I did a /usr/sbin/exabgp --fi > /etc/exabgp/exabgp.env. How can I change the logging destination or any other parameters in the env file?
4. How can I run exabgp continuously? So if the VM reboots I would like exabgp to auto start.
5. Are there any other healthchecks I should be performing?

Thanks

**Comment by thomas-mangin** [comment]
1. it is not a real configuration (from the IP) but sure, it looks right
2. for 3.4 yes, for 4.0 you need to read the message you are getting from exabgp. if you have to use a base for a script please use https://github.com/Exa-Networks/exabgp/blob/master/etc/exabgp/processes/read-write.py
3. run exabgp --help the answer is there (because I can not remember myself)
4. this is OS management and not ExaBGP, do what your distro does, init and systemd script / example are available in the repo.
5. does it work? if not using "-d" to get lots of debugging and find why. 

Good luck.
