### ISSUE TITLE
exaBGP_Home directory is not found after installing exaBGP in ubuntu 16.0.4

### ISSUE THREAD

**Issue by ksp13** [Exa-Networks/exabgp#759]
##### ISSUE TYPE
 - Bug Report

##### VERSION
ExaBGP : 3.4.13
Python : 2.7.12 (default, Nov 19 2016, 06:48:10)  [GCC 5.4.0 20160609]
Uname  : #166-Ubuntu SMP Wed May 3 12:18:55 UTC 2017

##### ENVIRONMENT 

```[exabgp.daemon]
user = 'exabgp'

[exabgp.tcp]
bind = '0.0.0.0'
```

##### SUMMARY
After installing exaBGP "exaBGP_home" directory is not getting created.

**Comment by thomas-mangin** [comment]
Happy xmas (if you celebrate it) ! 

You are making a statement but I can not understand what your problem is. Could you please be clearer with what happened and what you think should have happened. How did you install ExaBGP ? What did happened ? What would you have expected to happen ? It looks like a packaging issue to me .. is it with Debian, Ubuntu, RedHat, Arch ?

**Comment by thomas-mangin** [comment]
@ksp13 as ExaBGP does not require an home directory (when ran it normally use nobody) and as you did not provide more information, I will close this issue but feel free to re-open it if you think something is still not right.
