### ISSUE TITLE
'state' message missing with exabgp 4.x

### ISSUE THREAD

**Issue by kennydaili** [Exa-Networks/exabgp#839]
Hi, i was using exabgp3.4 before, for some reason, i need to upgrade to exabgp4.x(latest version 4.0.6), but i find the 'state' message is missing. There are many places in my program that rely on state messages. So, could you pls add the 'state' message back?

State message was controlled by configure 'neighbor-changes' before, but in latest version, it's cancelled:
```
receive {
    neighbor-changes;
}
```
attach source code(in exabgp/lib/exabgp/configuration/neighbor/api.py):
```
for way in ('send','receive'):
	for name in ('parsed','packets','consolidate','open', 'update', 'notification', 'keepalive', 'refresh', 'operational'):
		ParseAPI.DEFAULT_API["%s-%s" % (way,name)] = []
```

following is my env:
```
17:05:13 | 118735 | welcome       | Thank you for using ExaBGP
17:05:13 | 118735 | version       | 4.0.6-daa3d6ba
17:05:13 | 118735 | interpreter   | 3.5.5 (default, Jul  4 2018, 11:25:06)  [GCC 4.8.5 20150623 (Red Hat 4.8.5-4)]
```

**Comment by thomas-mangin** [comment]
Hello @kennydaili,

The code you reference is modifying the class dict which does contain `neighbor-changes`.
```
class ParseAPI (Section):
	[...]
	DEFAULT_API = {
		'neighbor-changes': [],
		[...]
	}
```

I do not rule out a bug in the code not parsing / sending the state update but it will not be caused by the code you reference.

I need to find some time to investigate. Also you do not provide enough of your configuration for me to attempt to reproduce the issue easily. Do you use template for example ?

**Comment by kennydaili** [comment]
Hi @thomas-mangin ,
Many Tks for your help, it's due to my configuration err.
Syntax is different with 3.4.
I go through api.py in full, and find the reason. Tks for your reminder. I will close this issue.

**Comment by thomas-mangin** [comment]
No issues - You can blame me for not documenting enough the project !
